FROM golang:1.24.1-alpine3.21 AS build

WORKDIR /azcopy

RUN apk add --no-cache \
    build-base \
    wget \
    bash \
    git

RUN wget "https://github.com/Azure/azure-storage-azcopy/archive/refs/tags/v10.28.1.tar.gz" -O src.tgz \
    && tar xf src.tgz --strip-components=1 \
    && go build -o azcopy \
    && ./azcopy --version

FROM postgres:alpine

COPY --from=build /azcopy/azcopy /usr/local/bin/azcopy

WORKDIR /backup