services:
  image-worker:
    build: ./backend
    command: npm run image-worker
    container_name: image-worker
    image: image-worker
    environment:
      FILES_DIR: "/usr/src/app/files"
      IMAGE_NAME: "image.jpg"
      PICSUM_URL: "https://picsum.photos/1200"
    volumes:
      - todo-files:/usr/src/app/files

  image-backend:
    build: ./backend
    command: npm run image-backend
    container_name: image-backend
    image: image-backend
    expose:
      - "3001"
    environment:
      PORT: 3001
      FILES_DIR: "/usr/src/app/files"
      IMAGE_NAME: "image.jpg"
    volumes:
      - todo-files:/usr/src/app/files
    depends_on:
      - image-worker

  todo-frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      IMAGE_FETCH_URL: "/image"
    depends_on:
      - image-worker
      - image-backend

  todo-backend:
    build: ./backend
    command: npm run todo-backend
    container_name: todo-backend
    image: todo-backend
    expose:
      - "3000"
    environment:
      PORT: 3000

volumes:
  todo-files:
