apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  labels:
    app: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-volumes
          persistentVolumeClaim:
            claimName: log-output-pvclaim

      containers:
        - name: pingpong-container
          image: pingpong
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: FILES_DIR
              value: "/usr/src/app/files"
            - name: FILE_NAME
              value: "ping.txt"
          volumeMounts:
            - name: shared-volumes
              mountPath: /usr/src/app/files
