apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- statefulset.yaml

images:
  - name: PINGPONG-API/IMAGE
    newName: dwkacr.azurecr.io/pingpong-backend

  - name: POSTGRES/IMAGE
    newName: postgres:16-alpine
