apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-generator-container
          image: log-generator
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001

        - name: log-reader-container
          image: log-reader
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
