apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-volumes
          persistentVolumeClaim:
            claimName: log-output-pvclaim

      containers:
        - name: log-generator-container
          image: log-generator
          imagePullPolicy: IfNotPresent
          env:
            - name: FILES_DIR
              value: "/usr/src/app/files"
            - name: FILE_NAME
              value: "log.txt"
          volumeMounts:
            - name: shared-volumes
              mountPath: /usr/src/app/files

        - name: log-reader-container
          image: log-reader
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: FILES_DIR
              value: "/usr/src/app/files"
            - name: GENERATOR_FILE_NAME
              value: "log.txt"
            - name: PINGPONG_FILE_NAME
              value: "ping.txt"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-volumes
              mountPath: /usr/src/app/files
