apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-reader-container
          image: backtoingressacr.azurecr.io/log-reader

          env:
            - name: PORT
              value: "3000"

            - name: GENERATOR_URL
              value: "http://log-generator-svc:80/"

            - name: PINGPONG_URL
              value: "http://pingpong-api-svc:80/pingpong"

            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE

            - name: INFO_CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  key: INFO_CONFIG_PATH
                  name: log-output-configmap

          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/files
              readOnly: true
          ports:
            - containerPort: 3000

      volumes:
        - name: config-volume
          configMap:
            name: log-output-configmap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator-deployment
  namespace: exercises
  labels:
    app: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator-container
          image: backtoingressacr.azurecr.io/log-generator

          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000