apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-pvclaim
spec:
  storageClassName: shared-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
