apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml
  - secret.yaml


images:
  - name: POSTGRES/IMAGE
    newName: postgres:16-alpine

  - name: BACKEND/IMAGE
    newName: dwkacr.azurecr.io/todo-backend:latest

  - name: FRONTEND/IMAGE
    newName: dwkacr.azurecr.io/todo-frontend:latest

  - name: BACKUP/IMAGE
    newName: dwkacr.azurecr.io/todo-backup:latest
