apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
  namespace: project
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: todo-pv
  hostPath:
    path: /tmp/todo-pv
