apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvclaim
  namespace: project
spec:
  storageClassName: local-path-retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi