apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvclaim
  namespace: project
spec:
  storageClassName: todo-pv
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
