services:
  log_generator:
    build: ./generator
    container_name: log-generator-container
    image: log-generator

  log_reader:
    build: ./reader
    container_name: log-reader-container
    image: log-reader
