name: Azure Automatic Deployment

on:
  push:

permissions:
  contents: read
  id-token: write

env:
  REGISTRY: "theprojectstep17acr.azurecr.io"
  ACR_NAME: "theprojectstep17acr"
  RESOURCE_GROUP: "e3.8-the-project-step-17"
  AKS_CLUSTER: "tps17-aks"

jobs:
  check-the-branch:
    runs-on: ubuntu-latest

    outputs:
      namespace: ${{ steps.branch.outputs.namespace }}

    steps:
      - name: Verify the branch name
        id: branch
        run: |
          branch="${GITHUB_REF#refs/heads/}"

          if [ -z "$branch" ]; then
            echo "Branch name is empty."
            exit 1
          fi

          if [ "$branch" = "main" ]; then
            namespace="project"
          else
            namespace="$branch"
          fi

          echo "namespace=$namespace" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs: check-the-branch
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: todo-frontend
            context: ./todo_app/frontend
            dockerfile: ./todo_app/frontend/dockerfile

          - image: todo-backend
            context: ./todo_app/backend
            dockerfile: ./todo_app/backend/dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Authenticate to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login \
            --name "${{ env.ACR_NAME }}"

      - name: Build and Push Image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.image }}:${{ github.sha }}

  deploy:
    needs: 
      - build-and-push
      - check-the-branch

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Authenticate to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --name "${{ env.AKS_CLUSTER }}" \
            --overwrite-existing

      - name: Set Kubernetes Images
        working-directory: ./todo_app/manifests
        run: |
          kustomize edit set image \
            BACKEND/IMAGE=${{ env.REGISTRY }}/todo-backend:${{ github.sha }}

          kustomize edit set image \
            FRONTEND/IMAGE=${{ env.REGISTRY }}/todo-frontend:${{ github.sha }}

      - name: Deploy Kubernetes Resources
        run: |
          kubectl create namespace "${{ needs.check-the-branch.outputs.namespace }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -k ./todo_app/manifests --namespace "${{ needs.check-the-branch.outputs.namespace }}"

      - name: Verify Backend Deployment
        run: |
          kubectl rollout status deployment/todo-backend-deployment \
            --namespace "${{ needs.check-the-branch.outputs.namespace }}"

      - name: Verify Frontend Deployment
        run: |
          kubectl rollout status deployment/todo-frontend-deployment \
            --namespace "${{ needs.check-the-branch.outputs.namespace }}"

      - name: Show Ingress
        run: |
          kubectl get ingress \
            --namespace "${{ needs.check-the-branch.outputs.namespace }}"